use_default_settings: true

server:
  secret_key: "qqq-shell-searxng-2026"
  bind_address: "0.0.0.0"
  port: 8088
  limiter: false
  image_proxy: false

search:
  formats:
    - html
    - json
  safe_search: 0
  engines:
    - name: duckduckgo
      disabled: false
    - name: google
      disabled: false
    - name: wikipedia
      disabled: false

ui:
  default_theme: simple
  default_locale: en

outgoing:
  request_timeout: 12.0
  max_request_timeout: 18.0
