use_default_settings: false

server:
  secret_key: "qqq-shell-searxng-2026"
  bind_address: "0.0.0.0"
  port: 8088
  limiter: false
  image_proxy: false
  default_doi_resolver: ""

search:
  formats:
    - html
    - json
  safe_search: 0
  autocomplete: ""
  ban_time_on_fail: 60
  max_ban_time_on_fail: 86400

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

ui:
  default_theme: simple
  default_locale: en

outgoing:
  request_timeout: 6.0
  max_request_timeout: 10.0
  useragent_suffix: ""
  proxies: {}
  retries: 1
  enable_http2: true

redis:
  url: false

plugins: []
enabled_plugins: []
checker:
  off_when_debug: false
  disabled: false
  scheduling: {}
